### ISSUE TITLE
Development flow broken at head

### ISSUE THREAD

**Issue by kayur** [nteract/commuter#238]
When I follow the developer instructions for commuter I get the error below. The error first appears with the [Oct 2nd update](https://github.com/nteract/commuter/commit/9fe32689f1bff207221caa266baff6742a429864
), which leads me to believe this is a problem with updating packages. 

I rolled back the [Sept 11th update](https://github.com/nteract/commuter/commit/3da7c6f09b8f548d39d60371d580b0055ada9a61
) and everything works.  I also confirmed that this is not only my computer.

**Error:** 
error  in ../frontend/icons/octicons.js
Module build failed: TypeError: .../octicons.js: Cannot read property '0' of null

**Comment by rgbkrk** [comment]
Thanks for reporting this @kayur! I haven't had a look at `master` for a bit, though it looks like @theengineear fixed the core issue stemming from a babel setup that was not being handled right by either next.js or styled-jsx (which are related since they're using the custom `next/babel` transform).

We could still use an update to the base packages here since we shouldn't stay on the next 4 beta (official 4 came out a bit ago).
